global using FriendzyBlog.Api;
global using FriendzyBlog.Data;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using MuonroiBuildingBlock.Application;
global using MuonroiBuildingBlock.Infrastructure;
global using MuonroiBuildingBlock.Infrastructure.Midleware;
global using System.Reflection;global using FriendzyBlog.Data.Seed;
global using MuonroiBuildingBlock.Entity;
global using MuonroiBuildingBlock.Contract.Constants;
global using Microsoft.Extensions.DependencyInjection;
global using MuonroiBuildingBlock.Common;
global using MuonroiBuildingBlock.Contract.Interfaces;
global using Serilog;
global using MuonroiBuildingBlock.Common.Logging;
